name: Production
values:
  - key: baseURL
    value: ''
    enabled: true
    type: default
  - key: authToken
    value: ''
    enabled: true
    type: secret
  - key: jiraEmail
    value: ''
    enabled: true
    type: default
  - key: jiraApiToken
    value: ''
    enabled: true
    type: secret
